In [2]:
import numpy as np
arr=np.array([[10,20],[40,30]]) #this represents multi-dimensional array
print(arr)
print(type(arr))
# since the output is not a comma separated value hence it is an array

[[10 20]
 [40 30]]
<class 'numpy.ndarray'>


In [8]:
#slicing in array
arr1=np.array([10,20,30,60,50])
print(arr1[0:3])
print(arr1[:4])
print(arr1[1:])
print(arr1[:])

[10 20 30]
[10 20 30 60]
[20 30 60 50]
[10 20 30 60 50]


In [19]:
#slicing in multi-dimensional array
arr2=np.array([[10,20,30,40],[50,60,70,80]])
print(arr2[0:2,0:3])
print(arr2[0,1:3]) # this 0 represents the first [] array which is at 0th position
print(arr2[1,0:3]) # represents second [array] which is at 1st position


[[10 20 30]
 [50 60 70]]
[20 30]
[50 60 70]


In [29]:
# inspecting an array
arr2=np.array([[10,20,30,40],[50,60,70,80],[101,102,103,104]])

print(np.shape(arr2)) # array dimensions
print (np.size(arr2)) # number of array elements
print(np.ndim(arr2)) # number of dimensions
print(type(arr2))
print(arr2.dtype) # datatype of array
print(len(arr2)) # length of array
print(arr2.astype(float)) # convert array to diff type

(3, 4)
12
2
<class 'numpy.ndarray'>
int32
3
[[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [101. 102. 103. 104.]]


In [38]:
# mathematical operations in array
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])

print(arr1+arr2)
print(np.add(arr1,arr2))

print(arr1-arr2)
print(np.subtract(arr1,arr2))

print(arr1*arr2)
print(np.multiply(arr1,arr2))

print(arr1/arr2)
print(np.divide(arr1,arr2))


[[ 60  80]
 [100 120]]
[[ 60  80]
 [100 120]]
[[-40 -40]
 [-40 -40]]
[[-40 -40]
 [-40 -40]]
[[ 500 1200]
 [2100 3200]]
[[ 500 1200]
 [2100 3200]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
# some other functions
arr1=np.array([[1,2],[3,4]])
arr2=np.array([3])

print(np.power(arr1,arr2))

arr3=np.array([4,81,25,100])
print(np.sqrt(arr3))

[[ 1  8]
 [27 64]]
[ 2.  9.  5. 10.]


In [48]:
# combining and spliting array
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
print(np.concatenate([arr1,arr2]))
print(np.hstack([arr1,arr2])) # horizontal concatenation
print(np.vstack([arr1,arr2])) # vertical concatenation


[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20 50 60]
 [30 40 70 80]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [51]:
# spliting an array
a=np.array([10,20,50,40,50,90,80])
b=np.array_split(a,5) # 5 shows the number of array in which u have to divide the given array
print(b)

[array([10, 20]), array([50, 40]), array([50]), array([90]), array([80])]


In [65]:
# adding and removing elements in arrays
arr=np.array([20,50,90,60])
arr1=np.array([[40,50],[60,70]])
print(np.append(arr,10))
print(np.append(arr1,100)) # adding element to 2-d array will convert the arrya into 1-d tahn add it and give o/p in 2-d

print(np.insert(arr,2,30)) #(array,index,value)
print(np.insert(arr1,3,[800,900]))

print(np.delete(arr,2))
print(np.delete(arr1,2))

[20 50 90 60 10]
[ 40  50  60  70 100]
[20 50 30 90 60]
[ 40  50  60 800 900  70]
[20 50 60]
[40 50 70]


In [11]:
# search,sort and filter array
arr=np.array([5,9,7,3,4,6])
arr1=np.array([[40,10],[20,10]])
print(np.sort(arr))
print(np.sort(arr1))

s=np.where(arr%2==0) #returns the position value
print(s)

arr2=np.array([1,2,3,5,9])
ss=np.searchsorted(arr2,3) # for using this we need to keep in mind that the array is sorted
print(ss)

arr3=np.array([20,30,40,50])
fa=[True,False,True,False] #used to filter the elements
new=arr3[fa]
print(new)

fa=arr3>26 # or fa=arr3%2==0 etc etc
new=arr3[fa]
print(new)



[3 4 5 6 7 9]
[[10 40]
 [10 20]]
(array([4, 5], dtype=int64),)
2
[20 40]
[30 40 50]


In [12]:
# aggregating functions
arr=np.array([5,9,7,3,4,6])

print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))
print(np.cumsum(arr))
print(np.mean(arr))


34
3
9
6
[ 5 14 21 24 28 34]
5.666666666666667


In [15]:
a=[100,150,199,458,214,170]
b=[10,20,40,60,90,50]

price=np.array(a)
quantity=np.array(b) 
print(price,"\n",quantity)
print()

c=np.cumprod([price,quantity])
print(c[1].sum())
c=np.cumprod([price,quantity], axis=0)
 print(c[1].sum())

[100 150 199 458 214 170] 
 [10 20 40 60 90 50]

15000
67200


In [21]:
#statistical function
import numpy as np
import statistics as stats
baked_food=[200,300,150,280,200,170,188]

a=np.array(baked_food)
print(np.mean(baked_food)) # sum of all the values/number of values
print(np.median(baked_food)) # first the array will get sorted and then median value will be taken out
print(stats.mode(baked_food)) # for using mode we need to import statistics 
print(np.std(baked_food)) # standard deviation

212.57142857142858
200.0
200
51.87583291684411


In [24]:
# corelation and regression
# -1 represent inversely proportional relationship
# 1 represent propotional reltionship 
# 0 mean no relationship

#positive correlation
tobacco_consumption=[30,40,10,50,60]
deaths=[100,105,120,112,169]
print(np.corrcoef([tobacco_consumption,deaths]))

#negative correlation
price=[300,100,350,150,200]
sales=[10,20,7,17,3]
print(np.corrcoef([price,sales]))


[[1.         0.52059651]
 [0.52059651 1.        ]]
[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
